trigger:
- master

variables:
  sdk_version: 2.1.603

jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  variables:
    patch: $[counter('myversioncounter', 0)]
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      packageType: sdk
      version: $(sdk_version)
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - powershell: .\build.ps1 -Target="Package"
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
  - task: CopyFiles@2
    inputs:
      contents: 'dist\**'
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'Package-$(patch)'
